services:
  stock-publisher:
    image: manuelbrunner/stock-publisher
    environment:
      - RABBITMQ_URL=amqp://stockmarket:supersecret123@rabbitmq:5672/
      - TICKER_INTERVAL=1
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: stockmarket
      RABBITMQ_DEFAULT_PASS: supersecret123

  mongo1:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db
      - ./mongo-keyfile:/etc/mongo-keyfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: guest
      MONGO_INITDB_ROOT_PASSWORD: guest
    command: >
      bash -c " chmod 400 /etc/mongo-keyfile && mongod --replSet rs0 --bind_ip_all --keyFile /etc/mongo-keyfile"

  mongo2:
    image: mongo:4.4
    ports:
      - "27018:27017"
    volumes:
      - mongo2_data:/data/db
      - ./mongo-keyfile:/etc/mongo-keyfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: guest
      MONGO_INITDB_ROOT_PASSWORD: guest
    command: >
      bash -c " chmod 400 /etc/mongo-keyfile && mongod --replSet rs0 --bind_ip_all --keyFile /etc/mongo-keyfile"

  mongo3:
    image: mongo:4.4
    ports:
      - "27019:27017"
    volumes:
      - mongo3_data:/data/db
      - ./mongo-keyfile:/etc/mongo-keyfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: guest
      MONGO_INITDB_ROOT_PASSWORD: guest
    command: >
      bash -c " chmod 400 /etc/mongo-keyfile && mongod --replSet rs0 --bind_ip_all --keyFile /etc/mongo-keyfile"

  mongo-setup:
    image: mongo:4.4
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    command: >
      bash -c " sleep 5; mongo --host mongo1:27017 -u guest -p guest --authenticationDatabase admin --eval 'rs.initiate({_id: \"rs0\", members: [{ _id: 0, host: \"mongo1:27017\" }, { _id: 1, host: \"mongo2:27018\" }, { _id: 2, host: \"mongo3:27019\" }]})'"

  consumer:
    image: oz96/consumer:v1
    environment:
      - RABBITMQ_URL=amqp://stockmarket:supersecret123@rabbitmq:5672/
      - MONGO_URL=mongodb://mongodb:27017/
      - QUEUE_NAME=stock_queue
    depends_on:
      - rabbitmq
      - mongo1
      - mongo2
      - mongo3

  stock-liveview1:
    image: manuelbrunner/stock-liveview
    environment:
      - MONGODB_URL=mongodb://mongo1:27017,mongo2:27018,mongo3:27019/?replicaSet=rs0
      - MONGODB_DB=stockmarket
      - MONGODB_COLLECTION=stocks
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3001:3000"

  stock-liveview2:
    image: manuelbrunner/stock-liveview
    environment:
      - MONGODB_URL=mongodb://mongo1:27017,mongo2:27018,mongo3:27019/?replicaSet=rs0
      - MONGODB_DB=stockmarket
      - MONGODB_COLLECTION=stocks
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3002:3000"

  nginx-loadbalancer:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - stock-liveview1
      - stock-liveview2

volumes:
  rabbitmq_data:
  mongo1_data:
  mongo2_data:
  mongo3_data:
